version: '2'
services:
  app:
    container_name: app_ruby_on_rails
    build: .
    environment:
      RAILS_ENV: development
      DATABASE_URL: mysql2://root:pass@mysql:3306
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3000:3000'
    volumes:
      - ./ruby_app:/usr/src/app
    links:
      - mysql
    command:  bash -c "bundle exec rails s -p 3000 -b '0.0.0.0'"
  mysql:
    container_name: mysql_ruby_on_rails
    image: mysql:5
    environment:
      MYSQL_ROOT_PASSWORD: 'pass'
    ports:
      - '3306:3306'
    volumes:
      - ./mysql-data:/var/lib/mysql
volumes:
  mysql-data:
    driver: local